/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Capuccino;
import modelo.Expresso;
import modelo.Latte;
import controlador.Maquina;
import modelo.Moka;
import java.awt.Color;
import java.util.Enumeration;
import javax.swing.ButtonGroup;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Samsung
 */
public class Cafematica extends javax.swing.JFrame {

    /**
     * Creates new form Cafematica
     */
    public Cafematica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBebida = new javax.swing.ButtonGroup();
        GrupoLeche = new javax.swing.ButtonGroup();
        GrupoAzucar = new javax.swing.ButtonGroup();
        GrupoSize = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Expresso = new javax.swing.JRadioButton();
        Latte = new javax.swing.JRadioButton();
        Capuchino = new javax.swing.JRadioButton();
        Moka = new javax.swing.JRadioButton();
        HotChoc = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        LecheD = new javax.swing.JRadioButton();
        LecheE = new javax.swing.JRadioButton();
        LecheS = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        CAzucar = new javax.swing.JRadioButton();
        SAzucar = new javax.swing.JRadioButton();
        EAzucar = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        PBCafe = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        PBLecheE = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        PBLecheD = new javax.swing.JProgressBar();
        PBLecheS = new javax.swing.JProgressBar();
        PBChoc = new javax.swing.JProgressBar();
        jLabel9 = new javax.swing.JLabel();
        PBAzucar = new javax.swing.JProgressBar();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Preparar = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        SeleccionLbl = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        SizeM = new javax.swing.JRadioButton();
        SizeS = new javax.swing.JRadioButton();
        SizeL = new javax.swing.JRadioButton();
        TUCafe = new javax.swing.JButton();
        TULecheE = new javax.swing.JButton();
        TULecheD = new javax.swing.JButton();
        TULecheS = new javax.swing.JButton();
        TUChoc = new javax.swing.JButton();
        TUAzucar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cafemática");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 18)); // NOI18N
        jLabel2.setText("Seleccione el producto");

        Expresso.setBackground(new java.awt.Color(255, 255, 255));
        GrupoBebida.add(Expresso);
        Expresso.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        Expresso.setToolTipText("");
        Expresso.setActionCommand("1");
        Expresso.setLabel("Expreso");
        Expresso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExpressoMouseClicked(evt);
            }
        });
        Expresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpressoActionPerformed(evt);
            }
        });

        Latte.setBackground(new java.awt.Color(255, 255, 255));
        GrupoBebida.add(Latte);
        Latte.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        Latte.setText("Latte");
        Latte.setActionCommand("2");
        Latte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LatteMouseClicked(evt);
            }
        });
        Latte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LatteActionPerformed(evt);
            }
        });

        Capuchino.setBackground(new java.awt.Color(255, 255, 255));
        GrupoBebida.add(Capuchino);
        Capuchino.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        Capuchino.setText("Capuchino");
        Capuchino.setActionCommand("3");
        Capuchino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CapuchinoMouseClicked(evt);
            }
        });

        Moka.setBackground(new java.awt.Color(255, 255, 255));
        GrupoBebida.add(Moka);
        Moka.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        Moka.setText("Moka");
        Moka.setActionCommand("4");
        Moka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MokaMouseClicked(evt);
            }
        });

        HotChoc.setBackground(new java.awt.Color(255, 255, 255));
        GrupoBebida.add(HotChoc);
        HotChoc.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        HotChoc.setForeground(new java.awt.Color(255, 0, 51));
        HotChoc.setText("Chocolate Caliente");
        HotChoc.setActionCommand("5");
        HotChoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HotChocMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HotChoc)
                    .addComponent(Moka)
                    .addComponent(Capuchino)
                    .addComponent(Latte)
                    .addComponent(Expresso)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Expresso)
                .addGap(18, 18, 18)
                .addComponent(Latte)
                .addGap(18, 18, 18)
                .addComponent(Capuchino)
                .addGap(18, 18, 18)
                .addComponent(Moka)
                .addGap(18, 18, 18)
                .addComponent(HotChoc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 18)); // NOI18N
        jLabel3.setText("Tipo de leche");

        LecheD.setBackground(new java.awt.Color(255, 255, 255));
        GrupoLeche.add(LecheD);
        LecheD.setFont(new java.awt.Font("Microsoft Tai Le", 1, 16)); // NOI18N
        LecheD.setText("Descremada");
        LecheD.setActionCommand("2");
        LecheD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LecheDMouseClicked(evt);
            }
        });

        LecheE.setBackground(new java.awt.Color(255, 255, 255));
        GrupoLeche.add(LecheE);
        LecheE.setFont(new java.awt.Font("Microsoft Tai Le", 1, 16)); // NOI18N
        LecheE.setText("Entera");
        LecheE.setActionCommand("1");
        LecheE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LecheEMouseClicked(evt);
            }
        });

        LecheS.setBackground(new java.awt.Color(255, 255, 255));
        GrupoLeche.add(LecheS);
        LecheS.setFont(new java.awt.Font("Microsoft Tai Le", 1, 16)); // NOI18N
        LecheS.setText("Soya");
        LecheS.setActionCommand("3");
        LecheS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LecheSMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LecheE)
                        .addGap(68, 68, 68)
                        .addComponent(LecheD)
                        .addGap(36, 36, 36)
                        .addComponent(LecheS)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LecheE, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LecheD, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LecheS, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 18)); // NOI18N
        jLabel4.setText("Azucar");

        CAzucar.setBackground(new java.awt.Color(255, 255, 255));
        GrupoAzucar.add(CAzucar);
        CAzucar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 16)); // NOI18N
        CAzucar.setText("Con azucar");
        CAzucar.setActionCommand("1");
        CAzucar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CAzucarMouseClicked(evt);
            }
        });

        SAzucar.setBackground(new java.awt.Color(255, 255, 255));
        GrupoAzucar.add(SAzucar);
        SAzucar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 16)); // NOI18N
        SAzucar.setText("Sin azucar");
        SAzucar.setActionCommand("0");
        SAzucar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SAzucarMouseClicked(evt);
            }
        });

        EAzucar.setBackground(new java.awt.Color(255, 255, 255));
        GrupoAzucar.add(EAzucar);
        EAzucar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 16)); // NOI18N
        EAzucar.setText("Extra azucar");
        EAzucar.setActionCommand("2");
        EAzucar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EAzucarMouseClicked(evt);
            }
        });
        EAzucar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EAzucarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(SAzucar)
                        .addGap(41, 41, 41)
                        .addComponent(CAzucar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EAzucar))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SAzucar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CAzucar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EAzucar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        PBCafe.setBackground(new java.awt.Color(255, 255, 255));
        PBCafe.setForeground(java.awt.Color.gray);
        PBCafe.setOrientation(1);
        PBCafe.setValue(100);

        jLabel5.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Café");

        PBLecheE.setBackground(new java.awt.Color(255, 255, 255));
        PBLecheE.setForeground(java.awt.Color.gray);
        PBLecheE.setOrientation(1);
        PBLecheE.setValue(100);

        jLabel6.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Leche");

        PBLecheD.setBackground(new java.awt.Color(255, 255, 255));
        PBLecheD.setForeground(java.awt.Color.gray);
        PBLecheD.setOrientation(1);
        PBLecheD.setValue(100);

        PBLecheS.setBackground(new java.awt.Color(255, 255, 255));
        PBLecheS.setForeground(java.awt.Color.gray);
        PBLecheS.setOrientation(1);
        PBLecheS.setValue(100);

        PBChoc.setBackground(new java.awt.Color(255, 255, 255));
        PBChoc.setForeground(java.awt.Color.gray);
        PBChoc.setOrientation(1);
        PBChoc.setValue(100);

        jLabel9.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Chocolate");

        PBAzucar.setBackground(new java.awt.Color(255, 255, 255));
        PBAzucar.setForeground(java.awt.Color.gray);
        PBAzucar.setOrientation(1);
        PBAzucar.setValue(100);

        jLabel10.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Azucar");

        jLabel11.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Entera");

        jLabel12.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Leche");

        jLabel13.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Descremada");

        jLabel14.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Leche");

        jLabel15.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("de Soya");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PBCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PBLecheE, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(PBLecheD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PBLecheS, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PBChoc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PBAzucar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(PBAzucar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(PBChoc, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(PBCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PBLecheE, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PBLecheS, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PBLecheD, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        Preparar.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        Preparar.setForeground(new java.awt.Color(0, 102, 51));
        Preparar.setText("<html>PREPARAR<BR>SELECCIÓN</html>");
        Preparar.setActionCommand("");
        Preparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrepararActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 0, 0));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("$1,200");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Total a pagar");

        SeleccionLbl.setFont(new java.awt.Font("Microsoft Tai Le", 1, 16)); // NOI18N
        SeleccionLbl.setForeground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SeleccionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(SeleccionLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 18)); // NOI18N
        jLabel8.setText("Tamaño");

        SizeM.setBackground(new java.awt.Color(255, 255, 255));
        GrupoSize.add(SizeM);
        SizeM.setFont(new java.awt.Font("Microsoft Tai Le", 1, 16)); // NOI18N
        SizeM.setText("Mediano");
        SizeM.setActionCommand("2");
        SizeM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SizeMMouseClicked(evt);
            }
        });

        SizeS.setBackground(new java.awt.Color(255, 255, 255));
        GrupoSize.add(SizeS);
        SizeS.setFont(new java.awt.Font("Microsoft Tai Le", 1, 16)); // NOI18N
        SizeS.setText("Pequeño");
        SizeS.setActionCommand("1");
        SizeS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SizeSMouseClicked(evt);
            }
        });
        SizeS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SizeSActionPerformed(evt);
            }
        });

        SizeL.setBackground(new java.awt.Color(255, 255, 255));
        GrupoSize.add(SizeL);
        SizeL.setFont(new java.awt.Font("Microsoft Tai Le", 1, 16)); // NOI18N
        SizeL.setText("Grande");
        SizeL.setActionCommand("3");
        SizeL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SizeLMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(SizeS)
                        .addGap(57, 57, 57)
                        .addComponent(SizeM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SizeL)
                        .addGap(39, 39, 39))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SizeS, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SizeM, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SizeL, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TUCafe.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        TUCafe.setForeground(new java.awt.Color(204, 0, 0));
        TUCafe.setText("<html>&uarr</html>");
        TUCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUCafeActionPerformed(evt);
            }
        });

        TULecheE.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        TULecheE.setForeground(new java.awt.Color(204, 0, 0));
        TULecheE.setText("<html>&uarr</html>");
        TULecheE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TULecheEActionPerformed(evt);
            }
        });

        TULecheD.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        TULecheD.setForeground(new java.awt.Color(204, 0, 0));
        TULecheD.setText("<html>&uarr</html>");
        TULecheD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TULecheDActionPerformed(evt);
            }
        });

        TULecheS.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        TULecheS.setForeground(new java.awt.Color(204, 0, 0));
        TULecheS.setText("<html>&uarr</html>");
        TULecheS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TULecheSActionPerformed(evt);
            }
        });

        TUChoc.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        TUChoc.setForeground(new java.awt.Color(204, 0, 0));
        TUChoc.setText("<html>&uarr</html>");
        TUChoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUChocActionPerformed(evt);
            }
        });

        TUAzucar.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        TUAzucar.setForeground(new java.awt.Color(204, 0, 0));
        TUAzucar.setText("<html>&uarr</html>");
        TUAzucar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUAzucarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Preparar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(TUCafe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(TULecheE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(TULecheD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(TULecheS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(TUChoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(TUAzucar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Preparar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TUCafe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TULecheE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TULecheD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TULecheS, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TUChoc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TUAzucar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExpressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpressoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpressoActionPerformed

    private void EAzucarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EAzucarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EAzucarActionPerformed

    private void PrepararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrepararActionPerformed
        switch (GetSelectedInt(GrupoBebida)){
            case 1://Expreso
                Expresso exp = new Expresso(GetSelectedInt(GrupoSize), GetSelectedInt(GrupoAzucar));
                break;
            case 2://Latte
                Latte lat = new Latte(GetSelectedInt(GrupoSize), GetSelectedInt(GrupoLeche), GetSelectedInt(GrupoAzucar));
                break;
            case 3://Capuchino
                Capuccino cap = new Capuccino(GetSelectedInt(GrupoSize), GetSelectedInt(GrupoLeche), GetSelectedInt(GrupoAzucar));
                break;
            case 4://Moka
                Moka mok = new Moka(GetSelectedInt(GrupoSize), GetSelectedInt(GrupoLeche), GetSelectedInt(GrupoAzucar));
                break;
            case 5://Chocolate Caliente
                break;
            
        }
        ActProgBar();
    }//GEN-LAST:event_PrepararActionPerformed

    private void ExpressoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpressoMouseClicked
        UpdateSelectionLbl();
    }//GEN-LAST:event_ExpressoMouseClicked

    private void LatteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LatteMouseClicked
        UpdateSelectionLbl();
    }//GEN-LAST:event_LatteMouseClicked

    private void CapuchinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CapuchinoMouseClicked
        UpdateSelectionLbl();
    }//GEN-LAST:event_CapuchinoMouseClicked

    private void MokaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MokaMouseClicked
        UpdateSelectionLbl();
    }//GEN-LAST:event_MokaMouseClicked

    private void HotChocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HotChocMouseClicked
        UpdateSelectionLbl();
    }//GEN-LAST:event_HotChocMouseClicked

    private void LecheEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LecheEMouseClicked
        UpdateSelectionLbl();
    }//GEN-LAST:event_LecheEMouseClicked

    private void LecheDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LecheDMouseClicked
        UpdateSelectionLbl();
    }//GEN-LAST:event_LecheDMouseClicked

    private void LecheSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LecheSMouseClicked
        UpdateSelectionLbl();
    }//GEN-LAST:event_LecheSMouseClicked

    private void SAzucarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SAzucarMouseClicked
        UpdateSelectionLbl();
    }//GEN-LAST:event_SAzucarMouseClicked

    private void CAzucarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CAzucarMouseClicked
        UpdateSelectionLbl();
    }//GEN-LAST:event_CAzucarMouseClicked

    private void EAzucarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EAzucarMouseClicked
        UpdateSelectionLbl();
    }//GEN-LAST:event_EAzucarMouseClicked

    private void SizeMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SizeMMouseClicked
        UpdateSelectionLbl();
    }//GEN-LAST:event_SizeMMouseClicked

    private void SizeSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SizeSMouseClicked
        UpdateSelectionLbl();
    }//GEN-LAST:event_SizeSMouseClicked

    private void SizeLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SizeLMouseClicked
        UpdateSelectionLbl();
    }//GEN-LAST:event_SizeLMouseClicked

    private void SizeSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SizeSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SizeSActionPerformed

    private void TUCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUCafeActionPerformed
        PBCafe.setValue(100);
        Maquina.stockDisponible()[0] = Maquina.maxCafe;
        PBCafe.setForeground(Color.GRAY);
    }//GEN-LAST:event_TUCafeActionPerformed

    private void TULecheEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TULecheEActionPerformed
        PBLecheE.setValue(100);
        PBLecheE.setForeground(Color.GRAY);
    }//GEN-LAST:event_TULecheEActionPerformed

    private void TULecheDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TULecheDActionPerformed
        PBLecheD.setValue(100);
        PBLecheD.setForeground(Color.GRAY);
    }//GEN-LAST:event_TULecheDActionPerformed

    private void TULecheSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TULecheSActionPerformed
        PBLecheS.setValue(100);
        PBLecheS.setForeground(Color.GRAY);
    }//GEN-LAST:event_TULecheSActionPerformed

    private void TUChocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUChocActionPerformed
        PBChoc.setValue(100);
        PBChoc.setForeground(Color.GRAY);
    }//GEN-LAST:event_TUChocActionPerformed

    private void TUAzucarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUAzucarActionPerformed
        PBAzucar.setValue(100);
        PBAzucar.setForeground(Color.GRAY);
    }//GEN-LAST:event_TUAzucarActionPerformed

    private void LatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LatteActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Hola");
    }//GEN-LAST:event_LatteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cafematica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cafematica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cafematica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cafematica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cafematica().setVisible(true);
            }
        });
    }
    
    public String GetSelected(ButtonGroup buttonGroup){
        //jPanel3.enable(true);
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    }
    
    public int GetSelectedInt(ButtonGroup buttonGroup){
        //jPanel3.enable(true);
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return Integer.parseInt(button.getActionCommand());
            }
        }
        return -1;
    }
    
    public void UpdateSelectionLbl(){
        if (GetSelected(GrupoBebida)!=null){
            if (GetSelected(GrupoLeche)==null){
                LecheE.setSelected(true);
            }
            if (GetSelected(GrupoAzucar)==null){
                SAzucar.setSelected(true);
            }
            if (GetSelected(GrupoSize)==null){
                SizeS.setSelected(true);
            }
            SeleccionLbl.setText("<html>Tipo de bebida:<BR>" + GetSelected(GrupoBebida) + "<br><br>Tamaño:<BR>" + GetSelected(GrupoSize) + "<br><br>Tipo de leche:<BR>" + GetSelected(GrupoLeche) + "<br><br>Azucar:<BR>" + GetSelected(GrupoAzucar) + "</html>");        
        }
    }
    
    public void ActProgBar(){
        int[] AuxArr = Maquina.stockDisponible();//new int[6];
        Color[] AuxArr2 = new Color[6];//new int[6];
        PBCafe.setValue(AuxArr[0]);
        PBLecheE.setValue(AuxArr[1]);
        PBLecheD.setValue(AuxArr[2]);
        PBLecheS.setValue(AuxArr[3]);
        PBChoc.setValue(AuxArr[4]);
        PBAzucar.setValue(AuxArr[5]);
        
        boolean[] alSt = Maquina.alertaStock();
        for(int i=0; i<6; i++){
            if (alSt[i]==true){
                AuxArr2[i] = Color.RED;
            }else{
                AuxArr2[i] = Color.GRAY;
            }
        }
        PBCafe.setForeground(AuxArr2[0]);
        PBLecheE.setForeground(AuxArr2[1]);
        PBLecheD.setForeground(AuxArr2[2]);
        PBLecheS.setForeground(AuxArr2[3]);
        PBChoc.setForeground(AuxArr2[4]);
        PBAzucar.setForeground(AuxArr2[5]);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton CAzucar;
    public javax.swing.JRadioButton Capuchino;
    public javax.swing.JRadioButton EAzucar;
    public javax.swing.JRadioButton Expresso;
    private javax.swing.ButtonGroup GrupoAzucar;
    private javax.swing.ButtonGroup GrupoBebida;
    private javax.swing.ButtonGroup GrupoLeche;
    private javax.swing.ButtonGroup GrupoSize;
    public javax.swing.JRadioButton HotChoc;
    public javax.swing.JRadioButton Latte;
    public javax.swing.JRadioButton LecheD;
    public javax.swing.JRadioButton LecheE;
    public javax.swing.JRadioButton LecheS;
    public javax.swing.JRadioButton Moka;
    public javax.swing.JProgressBar PBAzucar;
    public javax.swing.JProgressBar PBCafe;
    public javax.swing.JProgressBar PBChoc;
    public javax.swing.JProgressBar PBLecheD;
    public javax.swing.JProgressBar PBLecheE;
    public javax.swing.JProgressBar PBLecheS;
    public javax.swing.JToggleButton Preparar;
    public javax.swing.JRadioButton SAzucar;
    private javax.swing.JLabel SeleccionLbl;
    public javax.swing.JRadioButton SizeL;
    public javax.swing.JRadioButton SizeM;
    public javax.swing.JRadioButton SizeS;
    public javax.swing.JButton TUAzucar;
    public javax.swing.JButton TUCafe;
    public javax.swing.JButton TUChoc;
    public javax.swing.JButton TULecheD;
    public javax.swing.JButton TULecheE;
    public javax.swing.JButton TULecheS;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JPanel jPanel7;
    public javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
